plugins {
    id 'net.fabricmc.fabric-loom' version '1.16-SNAPSHOT'
}

version = '1.0'
base.archivesName = "modid"

loom {
// The following code makes impossible to setup Gradle projects
//    mixin {
//        useLegacyMixinAp = true
//        defaultRefmapName = actualmodid + ".refmap.json"
//    }

    if (file("src/main/resources/META-INF/pjs_enhanced_gold_neoforge.classtweaker").exists())
        accessWidenerPath = file("src/main/resources/META-INF/pjs_enhanced_gold_neoforge.classtweaker")
}

dependencies {
    minecraft "com.mojang:minecraft:26.1.2"
    implementation "net.fabricmc:fabric-loader:0.19.3"

    // Fabric API
    implementation "net.fabricmc.fabric-api:fabric-api:0.150.0+26.1.2"
}

// We need to do this because MCreator doesn't allow to split armor textures in multiple folders
build {
    doLast {
        copy {
            from 'src/main/resources/assets/dev_fabric_2612/textures/entity/equipment/humanoid/'
            into 'src/main/resources/assets/dev_fabric_2612/textures/entity/equipment/humanoid_leggings/'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

apply from: 'mcreator.gradle'